title: Darko Lukić
email: lukicdarkoo@gmail.com
baseurl: ''
url: ''

excerpt_separator: <!--more-->
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: 'project'
